title: "Kacie Wielgus (Buzzard)"
description: "Speaker • Inclusion Consultant • Writer"

url: ""
baseurl: ""

markdown: kramdown
theme: null

permalink: pretty

collections:
  excerpts:
    output: true
    permalink: /excerpts/:name/

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: posts
    values:
      layout: post

include:
  - assets
